### ISSUE TITLE
210815 TO DO

### ISSUE THREAD

**Issue by recordbuffer** [semo41105/custom-erProject#17]
- [x] 화면 합치기
- [x] 사진 편집 툴 의논
- [x] 회원 기능
     - [x] 로그인
     - [x] 로그인 실패 > alert
     - [x] 로그아웃
- [ ] 상품 관리 기능 
     - [ ] 상품 업로드 / 수정 / 삭제

**Comment by semo41105** [comment]
- 사진 편집 툴 의논 내용
상품 이미지 위에 사진 영역을 만들어두고 사진을 업로드하면 미리 볼 수 있는 정도까지 구현

**Comment by ksmles36** [comment]
우리꺼는 현재
dto -> 엔티티 : 빌더패턴
엔티티 -> dto : ModelMapper

====================

dto 와 entity 간의 변환에 여러가지 방법이 있는 듯 하다
1. 그냥 단순하게 get, set 써서 수작업으로 옮기기
2. 빌더패턴을 사용해서 toEntity, toDto 하는 식
3. ModelMapper 를 사용해서 .map 해서 옮겨 담는 식

아마 취향차이로 사용하는 듯? 
 근데 혹시 진행하다보면 각각의 방법의 장단점이나 취약점을 발견할 수 있을 지도?

일단 우리는 진행할 때 알아서 저 방법들 중에서 사용하는 걸로~

**Comment by ksmles36** [comment]
Address @Embedded 관련 문제
회원 로그인 시 조회 할 때 address가 city, zipcode... 등으로 풀어지지가 않아서 데이터가 안 담아짐

**Comment by semo41105** [comment]
- [x] 상품 이미지, 옵션 수정
     - [x] 티셔츠 외 상품들 단일화
     - [x] 이미지 사이즈 맞추기
